spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true

  data:
    mongodb:
      url : mongodb://127.0.0.1:27017
      database : webflux

  thymeleaf:
    cache: false

logging:
  level:
    web: DEBUG
